### ISSUE TITLE
Data race in CSession::syncSendRequest

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/DDS#254]
**Affects**: `2.5.46.g8de60ef`
**OS**: Linux Fedora 30, GCC 9.1.1
**Boost**: `1.69.0`

When compiling and running our tests with the ThreadSanitizer, it detects a data race on a condition variable every time we call `CSession::syncSendRequest`, similar to the following:

```
==================
WARNING: ThreadSanitizer: data race (pid=16759)
  Write of size 8 at 0x7ffe14ebb2f0 by main thread:
    #0 pthread_cond_destroy <null> (libtsan.so.0+0x2e5ba)
    #1 void dds::tools_api::CSession::syncSendRequest<dds::tools_api::SBaseRequestImpl<dds::tools_api::SAgentInfoRequestData, dds::tools_api::SAgentInfoResponseData> >(dds::tools_api::SBaseRequestImpl<dds::tools_api::SAgentInfoRequestData, dds::tools_api::SAgentInfoResponseData>::request_t const&, dds::tools_api::SBaseRequestImpl<dds::tools_api::SAgentInfoRequestData, dds::tools_api::SAgentInfoResponseData>::responseVector_t&, std::chrono::duration<long, std::ratio<1l, 1l> > const&, std::ostream*) <null> (libdds_tools_lib.so+0x27779f)
    #2 fair::mq::test::TopologyFixture::SetUp() /home/dklein/projects/FairMQ3/test/sdk/Fixtures.h:66 (testsuite_SDK+0x46a508)
    #3 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (testsuite_SDK+0x4999aa)
    #4 __libc_start_main <null> (libc.so.6+0x23f32)

  Previous read of size 8 at 0x7ffe14ebb2f0 by thread T2:
    #0 pthread_cond_broadcast <null> (libtsan.so.0+0x2e497)
    #1 std::condition_variable::notify_all() <null> (libstdc++.so.6+0xd070c)

  Location is stack of main thread.

  Location is global '<null>' at 0x000000000000 ([stack]+0x00000001e2f0)

  Thread T2 (tid=16783, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2de12)
    #1 boost::thread::start_thread_noexcept() <null> (libboost_thread.so.1.69.0+0x103a7)
    #2 fair::mq::test::TopologyFixture::TopologyFixture() /home/dklein/projects/FairMQ3/test/sdk/Fixtures.h:50 (testsuite_SDK+0x45c6a7)
    #3 Topology_AsyncChangeState_Test /home/dklein/projects/FairMQ3/test/sdk/_topology.cxx:48 (testsuite_SDK+0x44dbb5)
    #4 CreateTest /home/dklein/projects/FairMQ3/build/extern/googletest_install/include/gtest/internal/gtest-internal.h:460 (testsuite_SDK+0x44dbb5)
    #5 testing::Test* testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(testing::internal::TestFactoryBase*, testing::Test* (testing::internal::TestFactoryBase::*)(), char const*) <null> (testsuite_SDK+0x499ab8)
    #6 __libc_start_main <null> (libc.so.6+0x23f32)

SUMMARY: ThreadSanitizer: data race (/lib64/libtsan.so.0+0x2e5ba) in __interceptor_pthread_cond_destroy
==================
```

Looking at the implementation, it reveals several problems:

* Spurious thread wake-ups are not handled at all
* The `CSession::SImpl::m_requests` container keeps request objects even after they are expired (unbounded growth)
  * -> captured references to the local condition variable and mutex become dangled references after the request has expired

The following attempt on a fix reduces the thread sanitizer warnings almost to none and in addition catches spurious wake-ups. Only every other run I see a single warning now (instead of 4 warnings every time before). But this needs more work, it also does not touch deleting expired requests in the asynchronous case at all:
```diff
diff --git a/dds-tools-lib/src/Tools.cpp b/dds-tools-lib/src/Tools.cpp
index 509126e..f6f81f9 100644
--- a/dds-tools-lib/src/Tools.cpp
+++ b/dds-tools-lib/src/Tools.cpp
@@ -411,6 +411,10 @@ void CSession::syncSendRequest(const typename Request_t::request_t& _requestData
                                const std::chrono::seconds& _timeout,
                                std::ostream* _out)
 {
+    std::condition_variable cv;
+    std::mutex mtx;
+    bool done(false);
+
     // TODO: FIXME: Dublicate output to DDS log?

     if (getSessionID().is_nil() || !IsRunning())
@@ -439,27 +443,32 @@ void CSession::syncSendRequest(const typename Request_t::request_t& _requestData
         }
     });

-    std::condition_variable cv;
-
-    requestPtr->setDoneCallback([&cv]() { cv.notify_all(); });
+    requestPtr->setDoneCallback([&cv, &mtx, &done]() {
+        {
+            std::lock_guard<std::mutex> lock(mtx);
+            done = true;
+        }
+        cv.notify_all();
+    });

     sendRequest<Request_t>(requestPtr);

-    std::mutex mtx;
-    std::unique_lock<std::mutex> lock(mtx);
     if (_timeout.count() == 0)
     {
-        cv.wait(lock);
+        std::unique_lock<std::mutex> lock(mtx);
+        cv.wait(lock, [&done]() { return done; });
     }
     else
     {
-        std::cv_status waitStatus = cv.wait_for(lock, _timeout);
-        if (waitStatus == std::cv_status::timeout)
+        std::unique_lock<std::mutex> lock(mtx);
+        if (!cv.wait_for(lock, _timeout, [&done]() { return done; }))
         {
             throw runtime_error("Timed out waiting for request");
         }
     }

+    m_impl->m_requests.erase(requestPtr->getRequest().m_requestID);
+
     if (_out != nullptr)
         *_out << "Request finished successfully" << endl;
 }
```

**Comment by dennisklein** [comment]
The proposed patch in #256 make the ThreadSanitizer heapy on my machine.

**Comment by AndreyLebedev** [comment]
@dennisklein Thanks for reporting the issue. We have fixed it in [2.5.47.ga7b10b1](https://github.com/FairRootGroup/DDS/tree/a7b10b11833fc3cc9f6450b09a92f002a640b44c).

**Comment by dennisklein** [comment]
Actually, it is only partially fixed. The lifetime issue is still present:

```
==================
WARNING: ThreadSanitizer: data race (pid=31795)
  Write of size 8 at 0x7ffe08cc4fd0 by main thread:
    #0 pthread_cond_destroy <null> (libtsan.so.0+0x2e5ba)
    #1 MiscCommon::CConditionEvent::~CConditionEvent() <null> (libdds_tools_lib.so+0x28020f)
    #2 fair::mq::test::TopologyFixture::SetUp() /home/dklein/projects/FairMQ3/test/sdk/Fixtures.h:66 (testsuite_SDK+0x46a508)
    #3 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (testsuite_SDK+0x4999aa)
    #4 __libc_start_main <null> (libc.so.6+0x23f32)

  Previous read of size 8 at 0x7ffe08cc4fd0 by thread T3:
    #0 pthread_cond_broadcast <null> (libtsan.so.0+0x2e497)
    #1 std::condition_variable::notify_all() <null> (libstdc++.so.6+0xd070c)

  Location is stack of main thread.

  Location is global '<null>' at 0x000000000000 ([stack]+0x00000001dfd0)

  Thread T3 (tid=31818, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2de12)
    #1 boost::thread::start_thread_noexcept() <null> (libboost_thread.so.1.69.0+0x103a7)
    #2 fair::mq::test::TopologyFixture::TopologyFixture() /home/dklein/projects/FairMQ3/test/sdk/Fixtures.h:50 (testsuite_SDK+0x45c6a7)
    #3 Topology_AsyncChangeState_Test /home/dklein/projects/FairMQ3/test/sdk/_topology.cxx:48 (testsuite_SDK+0x44dbb5)
    #4 CreateTest /home/dklein/projects/FairMQ3/build/extern/googletest_install/include/gtest/internal/gtest-internal.h:460 (testsuite_SDK+0x44dbb5)
    #5 testing::Test* testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(testing::internal::TestFactoryBase*, testing::Test* (testing::internal::TestFactoryBase::*)(), char const*) <null> (testsuite_SDK+0x499ab8)
    #6 __libc_start_main <null> (libc.so.6+0x23f32)

SUMMARY: ThreadSanitizer: data race (/lib64/libtsan.so.0+0x2e5ba) in __interceptor_pthread_cond_destroy
==================
```
